/******************************************************************************/
/****  Módulo: SEPARAÇÃO DE MERCADORIAS (Picking)                          ****/
/****                                                                       ****/
/****  Separação avulsa: importa os itens de um PEDIDO_VENDA ou de uma     ****/
/****  NOTA (fiscal) já existente para uma lista de separação própria.      ****/
/****  O operador bipa a posição de onde está retirando e o produto,       ****/
/****  a baixa do estoque endereçado usa a mesma lógica de                 ****/
/****  WMS_ESTOQUE_POSICAO (EstoquePosicao::darSaida).                     ****/
/******************************************************************************/

CREATE GENERATOR GEN_WMS_SEPARACAO_ID;
SET GENERATOR GEN_WMS_SEPARACAO_ID TO 0;

CREATE GENERATOR GEN_WMS_SEPARACAO_ITEM_ID;
SET GENERATOR GEN_WMS_SEPARACAO_ITEM_ID TO 0;

CREATE GENERATOR GEN_WMS_SEPARACAO_RETIRADA_ID;
SET GENERATOR GEN_WMS_SEPARACAO_RETIRADA_ID TO 0;

CREATE TABLE WMS_SEPARACAO (
    ID_SEPARACAO          INTEGER NOT NULL,
    ORIGEM                CHAR(1) NOT NULL,     /* P = Pedido de Venda, N = Nota Fiscal */
    ID_ORIGEM             INTEGER,              /* ID_PEDIDO_VENDA ou ID_NOTA de onde foi importado */
    NUMERO_DOCUMENTO      INTEGER,
    CLIENTE               VARCHAR(20),
    DATA_PEDIDO           DATE,
    STATUS                VARCHAR(15) DEFAULT 'AGUARDANDO' NOT NULL, /* AGUARDANDO, SEPARANDO, SEPARADO, CANCELADO */
    OBSERVACAO            VARCHAR(300),
    ID_USUARIO_IMPORTACAO INTEGER,
    DATA_IMPORTACAO       TIMESTAMP,
    ID_USUARIO_CONCLUSAO  INTEGER,
    DATA_CONCLUSAO        TIMESTAMP,
    CONSTRAINT PK_WMS_SEPARACAO PRIMARY KEY (ID_SEPARACAO)
);

CREATE INDEX IDX_WMS_SEPARACAO_ORIGEM ON WMS_SEPARACAO (ORIGEM, ID_ORIGEM);
CREATE INDEX IDX_WMS_SEPARACAO_STATUS ON WMS_SEPARACAO (STATUS);

CREATE TABLE WMS_SEPARACAO_ITEMS (
    ID_ITEM             INTEGER NOT NULL,
    ID_SEPARACAO        INTEGER NOT NULL,
    ID_PRODUTO          INTEGER NOT NULL,
    LOTE_SUGERIDO       VARCHAR(50),
    QUANTIDADE_PEDIDO   NUMERIC(18,4) NOT NULL,
    QUANTIDADE_SEPARADA NUMERIC(18,4) DEFAULT 0,
    OBSERVACAO          VARCHAR(200),
    CONSTRAINT PK_WMS_SEPARACAO_ITEMS PRIMARY KEY (ID_ITEM),
    CONSTRAINT FK_WMS_SEPITEM_SEPARACAO FOREIGN KEY (ID_SEPARACAO) REFERENCES WMS_SEPARACAO (ID_SEPARACAO)
);

CREATE INDEX IDX_WMS_SEPITEM_SEPARACAO ON WMS_SEPARACAO_ITEMS (ID_SEPARACAO);
CREATE INDEX IDX_WMS_SEPITEM_PRODUTO ON WMS_SEPARACAO_ITEMS (ID_PRODUTO);

/* Detalhe de cada retirada física feita para separar um item (permite que um
   mesmo item seja separado de várias posições/lotes diferentes até
   completar a quantidade pedida). */
CREATE TABLE WMS_SEPARACAO_RETIRADAS (
    ID_RETIRADA    INTEGER NOT NULL,
    ID_ITEM        INTEGER NOT NULL,
    ID_POSICAO     INTEGER NOT NULL,
    LOTE           VARCHAR(50),
    QUANTIDADE     NUMERIC(18,4) NOT NULL,
    ID_USUARIO     INTEGER,
    DATA_RETIRADA  TIMESTAMP,
    CONSTRAINT PK_WMS_SEPARACAO_RETIRADAS PRIMARY KEY (ID_RETIRADA),
    CONSTRAINT FK_WMS_SEPRET_ITEM FOREIGN KEY (ID_ITEM) REFERENCES WMS_SEPARACAO_ITEMS (ID_ITEM),
    CONSTRAINT FK_WMS_SEPRET_POSICAO FOREIGN KEY (ID_POSICAO) REFERENCES WMS_POSICAO (ID_POSICAO)
);

CREATE INDEX IDX_WMS_SEPRET_ITEM ON WMS_SEPARACAO_RETIRADAS (ID_ITEM);

SET TERM ^ ;

CREATE TRIGGER WMS_SEPARACAO_BI FOR WMS_SEPARACAO
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.ID_SEPARACAO IS NULL) THEN NEW.ID_SEPARACAO = GEN_ID(GEN_WMS_SEPARACAO_ID, 1);
  IF (NEW.DATA_IMPORTACAO IS NULL) THEN NEW.DATA_IMPORTACAO = CURRENT_TIMESTAMP;
  IF (NEW.STATUS IS NULL) THEN NEW.STATUS = 'AGUARDANDO';
END
^

CREATE TRIGGER WMS_SEPARACAO_ITEMS_BI FOR WMS_SEPARACAO_ITEMS
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.ID_ITEM IS NULL) THEN NEW.ID_ITEM = GEN_ID(GEN_WMS_SEPARACAO_ITEM_ID, 1);
  IF (NEW.QUANTIDADE_SEPARADA IS NULL) THEN NEW.QUANTIDADE_SEPARADA = 0;
END
^

CREATE TRIGGER WMS_SEPARACAO_RETIRADAS_BI FOR WMS_SEPARACAO_RETIRADAS
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.ID_RETIRADA IS NULL) THEN NEW.ID_RETIRADA = GEN_ID(GEN_WMS_SEPARACAO_RETIRADA_ID, 1);
  IF (NEW.DATA_RETIRADA IS NULL) THEN NEW.DATA_RETIRADA = CURRENT_TIMESTAMP;
END
^

SET TERM ; ^
